name: Checkout
on: [push]
jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: Display files before checkout
              run: ls -a
            - name: Checkout
              run: |
                  git init
                  git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                  git fetch origin
                  git checkout main 
                  # here the branch is hardcoded which is not good, we need to be branch specific
            - name: Display files after checkout
              run: |
                  pwd
                  ls -a