name: Simple Action
on: [push]
jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple Action
              id: greet
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: 'My Self'
            - name: Log Greeting Time
              run: echo "The greeting time {{ steps.greet.outputs.time }}"
